DROP SCHEMA IF EXISTS DB_PELICULAS;
CREATE SCHEMA IF NOT EXISTS DB_PELICULAS;
USE DB_PELICULAS;

CREATE TABLE USUARIO(
	ID_USUARIO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) UNIQUE NOT NULL,
    PASS VARCHAR(50) NOT NULL,
    ROL ENUM ('ADMIN', 'USUARIO') NOT NULL DEFAULT 'USUARIO'
);

CREATE TABLE PELICULA(
	ID_PELICULA INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	TITULO VARCHAR(255) NOT NULL,
	SINOPSIS TEXT
);

CREATE TABLE COMENTARIO(
	ID_COMENTARIO INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ID_PELICULA INT UNSIGNED NOT NULL,
	ID_USUARIO INT UNSIGNED NOT NULL,
	TEXTO_COMENTARIO TEXT,
    
    FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE VALORACION(
	ID_VALORACION INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	ID_PELICULA INT UNSIGNED NOT NULL,
	ID_USUARIO INT UNSIGNED NOT NULL,
	NOTA_VALORACION TINYINT 
		CONSTRAINT CHECK (NOTA_VALORACION BETWEEN 1 AND 10),
    
    FOREIGN KEY (ID_PELICULA) REFERENCES PELICULA(ID_PELICULA),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    
    CONSTRAINT UNIQUE(ID_PELICULA, ID_USUARIO)
);

INSERT INTO USUARIO(NOMBRE, EMAIL, PASS) VALUES
("FULANO DE COPAS", "FULANO@DECOPAS.COM", "123"),
("FULANO DE BASTOS", "FULANO@DEBASTOS.COM", "1234"),
("FULANO DE ESPADAS", "FULANO@DEESPADAS.COM", "1234"),
("FULANO DE OROS", "FULANO@DEOROS.COM", "1234");

INSERT INTO PELICULA(TITULO, SINOPSIS) VALUES
("BLADE RUNNER", "HARRISON FORD LE GUSTAN LAS ROBOTS"),
("TERMINATOR", "SWARZCHSENAGGER VULEVE"),
("LA MOSCA", "EL DE JURASSIC PARK SE CLONA REGULAR");

INSERT INTO VALORACION(ID_USUARIO, ID_PELICULA, NOTA_VALORACION) VALUES
(1, 1, 3),
(2, 1, 8),
(3, 1, 9),
(1, 2, 8),
(2, 2, 8),
(3, 2, 7),
(4, 2, 6);

INSERT INTO COMENTARIO(ID_USUARIO, ID_PELICULA, TEXTO_COMENTARIO) VALUES
(1, 1, "ME FLIPA"),
(2, 1, "NO PILLO EL FINAL, ES UN ROBOT O NO?"),
(3, 1, "QUE JOVEN ESTÁ HARRISON FORD"),
(3, 1, "GRAN DOBLAJE"),
(1, 2, "SAJ(Y?)ONARA BABY");






