CREATE SCHEMA DB_USUARIOS;
USE DB_USUARIOS;

CREATE TABLE USUARIO(
	ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(50),
    EDAD TINYINT UNSIGNED
);

INSERT INTO USUARIO(NOMBRE, EDAD) VALUES
('Pedro Sánchez', 56),
('M. Rajoy?', 63),
('Cococmocho', 59),
('Rufián', 43);
